version = "1.0"

[main]
name.en = "HedgeDoc configuration"
name.fr = "Configuration de HedgeDoc"
services = ["__APP__"]

    [main.config]
    name.en = "Configuration Options"
    name.fr = "Options de configuration"

        [main.config.allow_anonymous]
        ask.en = "Allow anonymous usage"
        ask.fr = "Autoriser l'utilisation anonyme"
        type = "boolean"
        yes = "true"
        no = "false"
        help.en = "Set to allow anonymous usage (default is true)."
        help.fr = "Définir pour autoriser l'utilisation anonyme (la valeur par défaut est vrai)."
        bind = "allowAnonymous:__INSTALL_DIR__/config.json"

        [main.config.allow_anonymous_edits]
        ask.en = "Allow anonymous edits"
        ask.fr = "Autoriser les modifications anonymes"
        type = "boolean"
        yes = "true"
        no = "false"
        help.en = "Allow users to select freely permission, allowing guests to edit existing notes."
        help.fr = "Permettez aux utilisateurs de sélectionner librement l'autorisation, permettant aux invités de modifier les notes existantes."
        bind = "allowAnonymousEdits:__INSTALL_DIR__/config.json"


        [main.config.allow_email_registration]
        ask.en = "Allow email registration"
        ask.fr = "Autoriser l'inscription par e-mail"
        type = "boolean"
        yes = "true"
        no = "false"
        help.en = "Set to allow registration of new accounts using an email address. If set to false, you can still create accounts using the command line."
        help.fr = "Configurer pour autoriser l'enregistrement de nouveaux comptes à l'aide d'une adresse e-mail. Si ce paramètre est défini sur « False », vous pouvez toujours créer des comptes en ligne de commande."
        bind = "allowEmailRegister:__INSTALL_DIR__/config.json"

        [main.config.allow_free_url]
        ask.en = "Allow new note creation"
        ask.fr = "Autoriser la création de nouvelles notes"
        type = "boolean"
        yes = "true"
        no = "false"
        help.en = "Set to allow new note creation by accessing a nonexistent note URL."
        help.fr = "Configurer pour autoriser la création de nouvelles notes en accédant à une URL de note inexistante."
        bind = "allowFreeURL:__INSTALL_DIR__/config.json"

        [main.config.require_free_url_authentication]
        ask.en = "Require FreeURL authentication"
        ask.fr = "Exiger l'authentification FreeURL"
        type = "boolean"
        yes = "true"
        no = "false"
        help.fr = "Set to require authentication for FreeURL mode style note creation."
        help.en = "Définir pour exiger une authentification pour la création de notes de style en mode FreeURL."
        bind = "requireFreeURLAuthentication:__INSTALL_DIR__/config.json"
