version = "1.0"

[main]
name.en = "HedgeDoc configuration"
name.fr = "Configuration de HedgeDoc"
services = ["__APP__"]

    [main.config]
    name.en = "Configuration Options"
    name.fr = "Options de configuration"

        [main.config.allow_anonymous]
        ask.en = "Allow anonymous usage"
        ask.fr = "Autoriser l'utilisation anonyme"
        type = "boolean"
        yes = "true"
        no = "false"
        help = "Set to allow anonymous usage (default is true)."
        bind = "allowAnonymous:__INSTALL_DIR__/config.json"

        [main.config.allow_anonymous_edits]
        ask.en = "Allow anonymous edits"
        ask.fr = "Autoriser les modifications anonymes"
        type = "boolean"
        yes = "true"
        no = "false"
        help = "Allow users to select freely permission, allowing guests to edit existing notes."
        bind = "allowAnonymousEdits:__INSTALL_DIR__/config.json"


        [main.config.allow_email_registration]
        ask.en = "Allow email registration"
        ask.fr = "Autoriser l'inscription par e-mail"
        type = "boolean"
        yes = "true"
        no = "false"
        help = "Set to allow registration of new accounts using an email address. If set to false, you can still create accounts using the command line."
        bind = "allowEmailRegister:__INSTALL_DIR__/config.json"

        [main.config.allow_free_url]
        ask.en = "Allow new note creation"
        ask.fr = "Autoriser la création de nouvelles notes"
        type = "boolean"
        yes = "true"
        no = "false"
        help = "Set to allow new note creation by accessing a nonexistent note URL. This is the behavior familiar from Etherpad."
        bind = "allowFreeURL:__INSTALL_DIR__/config.json"

        [main.config.require_free_url_authentication]
        ask.en = "Require FreeURL authentication"
        ask.fr = "Exiger l'authentification FreeURL"
        type = "boolean"
        yes = "true"
        no = "false"
        help = "Set to require authentication for FreeURL mode style note creation."
        bind = "requireFreeURLAuthentication:__INSTALL_DIR__/config.json"



