test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.f601a56a.name = "Upgrade from 1.9.7~ynh2"
