#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================
ynh_script_progression --message="Loading installation settings..." --weight=1

allow_anonymous=$(ynh_app_setting_get --app=$app --key=allow_anonymous)
allow_anonymous_edits=$(ynh_app_setting_get --app=$app --key=allow_anonymous_edits)
allow_email_registration=$(ynh_app_setting_get --app=$app --key=allow_email_registration)
allow_free_url=$(ynh_app_setting_get --app=$app --key=allow_free_url)
require_free_url_authentication=$(ynh_app_setting_get --app=$app --key=require_free_url_authentication)

#=================================================
# STANDARD MODIFICATIONS
#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Stopping a systemd service..." --weight=1

ynh_systemd_action --service_name=$app --action=stop --log_path=systemd

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression --message="Updating NGINX web server configuration..." --weight=1

ynh_change_url_nginx_config

#=================================================
# SPECIFIC MODIFICATIONS
#=================================================
# CONFIGURE HEDGEDOC
#=================================================

ynh_backup_if_checksum_is_different --file="$install_dir/config.json"

domain=$new_domain
url_path=${new_path#/}

ynh_add_config --template="../conf/config.json.example" --destination="$install_dir/config.json"

chmod 400 "$install_dir/config.json"
chown $app:$app "$install_dir/config.json"

#=================================================
# GENERIC FINALISATION
#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting a systemd service..." --weight=1

# Start a systemd service
ynh_systemd_action --service_name=$app --action=start --log_path=systemd --line_match="HTTP Server listening"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Change of URL completed for $app" --last
