#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
# REMOVE SYSTEMD SERVICE 
#=================================================
ynh_script_progression --message="Removing system configurations related to $app..." --weight=1

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_exec_warn_less yunohost service status ${app}_backend >/dev/null
then
	ynh_script_progression --message="Removing ${app}_backend service..." --weight=1
	yunohost service remove ${app}_backend
fi

if ynh_exec_warn_less yunohost service status ${app}_frontend >/dev/null
then
	ynh_script_progression --message="Removing ${app}_frontend service..." --weight=1
	yunohost service remove ${app}_frontend
fi

# Remove the dedicated systemd config
ynh_remove_systemd_config --service=${app}_backend
ynh_remove_systemd_config --service=${app}_frontend

ynh_remove_nodejs

ynh_remove_nginx_config

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
