#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# CHECK VERSION
#=================================================

upgrade_type=$(ynh_check_app_version_changed)

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression --message="Ensuring downward compatibility..." --weight=1

if [ -z "${allow_anonymous:-}" ]; then
	allow_anonymous="false"
	ynh_app_setting_set --app=$app --key=allow_anonymous --value=$allow_anonymous
fi

if [ -z "${allow_anonymous_edits:-}" ]; then
	allow_anonymous_edits="false"
	ynh_app_setting_set --app=$app --key=allow_anonymous_edits --value=$allow_anonymous_edits
fi

if [ -z "${allow_email_registration:-}" ]; then
	allow_email_registration="false"
	ynh_app_setting_set --app=$app --key=allow_email_registration --value=$allow_email_registration
fi

if [ -z "${allow_free_url:-}" ]; then
	allow_free_url="false"
	ynh_app_setting_set --app=$app --key=allow_free_url --value=$allow_free_url
fi

if [ -z "${require_free_url_authentication:-}" ]; then
	require_free_url_authentication="false"
	ynh_app_setting_set --app=$app --key=require_free_url_authentication --value=$require_free_url_authentication
fi

#=================================================
# STANDARD UPGRADE STEPS
#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Stopping a systemd service..." --weight=1

ynh_systemd_action --service_name=$app --action=stop --log_path=systemd

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

if [ "$upgrade_type" == "UPGRADE_APP" ]
then
	ynh_script_progression --message="Upgrading source files..." --weight=10

	# Download, check integrity, uncompress and patch the source from app.src
	ynh_setup_source --dest_dir=$install_dir --keep="config.json"
fi

chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression --message="Upgrading system configurations related to $app..." --weight=1

ynh_add_nginx_config

ynh_exec_warn_less ynh_install_nodejs --nodejs_version=$nodejs_version

ynh_add_systemd_config

yunohost service add $app --description="Collaborative Markdown editor" --log="/var/log/$app/$app.log"

#==============================================
# INSTALL HEDGEDOC
#==============================================

if [ "$upgrade_type" == "UPGRADE_APP" ]
then
	ynh_script_progression --message="Building $app... (this will take some time and resources!)" --weight=10

	pushd "$install_dir"
		ynh_secure_remove /usr/local/share/.cache/yarn 
		ynh_use_nodejs
		ynh_exec_warn_less sudo -u $app env $ynh_node_load_PATH yarn workspaces focus --production
		ynh_exec_warn_less sudo -u $app env $ynh_node_load_PATH yarn cache clean
	popd
fi

#=================================================
# MODIFY A CONFIG FILE
#=================================================
ynh_script_progression --message="Modifying a config file..." --weight=1

url_path=${path#/}
ynh_add_config --template="config.json.example" --destination="$install_dir/config.json"

chmod 600 "$install_dir/config.json"
chown $app:$app "$install_dir/config.json"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting a systemd service..." --weight=1

ynh_systemd_action --service_name=$app --action=start --log_path=systemd --line_match="HTTP Server listening"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Upgrade of $app completed" --last
