#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

# FIXME: maybe replace with: ynh_app_setting_set_default --key=allow_anonymous --value="false"
if [ -z "${allow_anonymous:-}" ]; then
	allow_anonymous="false"
	ynh_app_setting_set --key=allow_anonymous --value=$allow_anonymous
fi

# FIXME: maybe replace with: ynh_app_setting_set_default --key=allow_anonymous_edits --value="false"
if [ -z "${allow_anonymous_edits:-}" ]; then
	allow_anonymous_edits="false"
	ynh_app_setting_set --key=allow_anonymous_edits --value=$allow_anonymous_edits
fi

# FIXME: maybe replace with: ynh_app_setting_set_default --key=allow_email_registration --value="false"
if [ -z "${allow_email_registration:-}" ]; then
	allow_email_registration="false"
	ynh_app_setting_set --key=allow_email_registration --value=$allow_email_registration
fi

# FIXME: maybe replace with: ynh_app_setting_set_default --key=allow_free_url --value="false"
if [ -z "${allow_free_url:-}" ]; then
	allow_free_url="false"
	ynh_app_setting_set --key=allow_free_url --value=$allow_free_url
fi

# FIXME: maybe replace with: ynh_app_setting_set_default --key=require_free_url_authentication --value="false"
if [ -z "${require_free_url_authentication:-}" ]; then
	require_free_url_authentication="false"
	ynh_app_setting_set --key=require_free_url_authentication --value=$require_free_url_authentication
fi

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action=stop --log_path=systemd

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir=$install_dir --keep="config.json"

chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_nodejs_install

ynh_config_add_systemd

yunohost service add $app --description="Collaborative Markdown editor" --log="/var/log/$app/$app.log"

#==============================================
# INSTALL HEDGEDOC
#==============================================
ynh_script_progression "Building $app... (this will take some time and resources!)"

pushd "$install_dir"
	ynh_safe_rm /usr/local/share/.cache/yarn

	ynh_hide_warnings ynh_exec_as_app node_load_PATH yarn workspaces focus --production
	ynh_hide_warnings ynh_exec_as_app node_load_PATH yarn cache clean
popd

#=================================================
# MODIFY A CONFIG FILE
#=================================================
ynh_script_progression "Updating configuration..."

url_path=${path#/}
ynh_config_add --template="config.json.example" --destination="$install_dir/config.json"

chmod 600 "$install_dir/config.json"
chown $app:$app "$install_dir/config.json"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action=start --log_path=systemd --wait_until="HTTP Server listening"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
